apiVersion: v1
kind: PipeSpec
metadata:
  name: github-ai-pr-review-demo
  owner: PlugPipe Team
  version: 1.0.0
  tags:
  - github
  - ai
  - code_review
  - demo
  doc: Focused demonstration of AI-powered pull request review capabilities
inputs: {}
pipeline:
- name: ai_code_review
  plug: llm_github_mcp
  config:
    github:
      auth_method: token
      token: '{{github_token}}'
    llm:
      provider: openai
      api_key: '{{openai_api_key}}'
      model: gpt-4
      temperature: 0.1
    automation_settings:
      auto_comment: true
  inputs:
    operation: review_pull_request
    owner: '{{repo_owner}}'
    repo: '{{repo_name}}'
    pr_number: '{{pr_number}}'
    review_criteria:
    - security
    - performance
    - maintainability
    - code_quality
    - testing
  outputs:
    ai_review: '{{llm_github_result}}'
    security_issues: '{{llm_github_result.security_analysis}}'
    performance_concerns: '{{llm_github_result.performance_analysis}}'
    recommendation: '{{llm_github_result.overall_recommendation}}'
  id: step_1
  uses: name
  with: {}
- name: ai_bug_detection
  plug: llm_github_mcp
  config:
    github:
      auth_method: token
      token: '{{github_token}}'
    llm:
      provider: openai
      api_key: '{{openai_api_key}}'
      model: gpt-4
  inputs:
    operation: spot_bugs
    owner: '{{repo_owner}}'
    repo: '{{repo_name}}'
    commit_range: HEAD~3..HEAD
  outputs:
    bug_findings: '{{llm_github_result}}'
    potential_bugs: '{{llm_github_result.bug_findings}}'
  id: step_2
  uses: name
  with: {}
- name: create_review_summary
  plug: github_integration
  config:
    auth_method: token
    token: '{{github_token}}'
  inputs:
    operation: create_issue
    owner: '{{repo_owner}}'
    repo: '{{repo_name}}'
    issue_data:
      title: '🤖 AI Code Review Summary - PR #{{pr_number}}'
      body: "# AI Code Review Summary for PR #{{pr_number}}\n\n**Generated by PlugPipe\
        \ LLM GitHub MCP Integration**\n\n## \U0001F4CB Review Overview\n**Pull Request:**\
        \ #{{pr_number}} - {{ai_review.pr_title}}\n**Author:** {{ai_review.author}}\n\
        **Files Changed:** {{ai_review.files_changed}}\n**Lines Added:** {{ai_review.changes_summary.additions}}\n\
        **Lines Deleted:** {{ai_review.changes_summary.deletions}}\n\n## \U0001F916\
        \ AI Analysis\n{{ai_review.ai_review}}\n\n## \U0001F512 Security Analysis\n\
        {% if security_issues.total_issues > 0 %}\n**Security Issues Found:** {{security_issues.total_issues}}\n\
        \n### Pattern-Based Security Issues:\n{% for issue in security_issues.pattern_based_issues\
        \ %}\n- **{{issue.vulnerability}}** in `{{issue.file}}` (Severity: {{issue.severity}})\n\
        {% endfor %}\n\n### AI Security Assessment:\n{{security_issues.ai_analysis}}\n\
        {% else %}\n✅ No significant security issues detected.\n{% endif %}\n\n##\
        \ ⚡ Performance Analysis\n{% if performance_concerns.total_concerns > 0 %}\n\
        **Performance Concerns:** {{performance_concerns.total_concerns}}\n\n{% for\
        \ concern in performance_concerns.pattern_based_concerns %}\n- **{{concern.concern}}**\
        \ in `{{concern.file}}` (Impact: {{concern.impact}})\n{% endfor %}\n\n###\
        \ AI Performance Assessment:\n{{performance_concerns.ai_analysis}}\n{% else\
        \ %}\n✅ No significant performance concerns identified.\n{% endif %}\n\n##\
        \ \U0001F41B Bug Detection Results\n**Commits Analyzed:** {{bug_findings.commits_analyzed}}\n\
        **Files Analyzed:** {{bug_findings.files_analyzed}}\n**Potential Bugs:** {{potential_bugs\
        \ | length}}\n\n{% if potential_bugs | length > 0 %}\n### Bug Findings:\n\
        {% for bug in potential_bugs %}\n- **{{bug.filename}}**: Risk Score {{bug.risk_score}}/10\n\
        \  - Potential Issues: {{bug.potential_bugs | length}}\n  - AI Analysis: {{bug.ai_analysis\
        \ | truncate(200)}}...\n{% endfor %}\n{% endif %}\n\n## \U0001F4CA Overall\
        \ Recommendation\n{{recommendation}}\n\n## \U0001F527 Action Items\n\n###\
        \ Immediate Actions:\n{% if security_issues.total_issues > 0 %}\n- [ ] Review\
        \ and address security vulnerabilities\n{% endif %}\n{% if performance_concerns.total_concerns\
        \ > 0 %}\n- [ ] Optimize performance bottlenecks\n{% endif %}\n{% if potential_bugs\
        \ | length > 0 %}\n- [ ] Investigate potential bug findings\n{% endif %}\n\
        \n### Quality Improvements:\n- [ ] Add comprehensive test coverage\n- [ ]\
        \ Update documentation if needed\n- [ ] Consider code refactoring opportunities\n\
        - [ ] Validate error handling paths\n\n---\n\n**Review Timestamp:** {{timestamp}}\n\
        **AI Provider:** OpenAI GPT-4\n**PlugPipe Version:** 1.0.0\n\n_This AI-powered\
        \ review demonstrates PlugPipe's intelligent code analysis capabilities._\n"
      labels:
      - ai-review
      - code-quality
      - pr-analysis
  outputs:
    review_issue_number: '{{github_result.number}}'
    review_issue_url: '{{github_result.html_url}}'
  id: step_3
  uses: name
  with: {}
- name: notify_ai_review
  plug: slack_messaging
  config:
    webhook_url: '{{slack_webhook}}'
    channel: '#code-review'
  inputs:
    operation: send_message
    message: '🤖 **AI Code Review Complete for PR #{{pr_number}}**


      **Repository:** {{repo_owner}}/{{repo_name}}

      **Author:** {{ai_review.author}}

      **Files Changed:** {{ai_review.files_changed}}


      ## 🔍 AI Analysis Summary

      {% if security_issues.total_issues > 0 %}

      🔒 **Security Issues:** {{security_issues.total_issues}} found

      {% else %}

      ✅ **Security:** No issues detected

      {% endif %}


      {% if performance_concerns.total_concerns > 0 %}

      ⚡ **Performance Concerns:** {{performance_concerns.total_concerns}} identified

      {% else %}

      ✅ **Performance:** No concerns identified

      {% endif %}


      {% if potential_bugs | length > 0 %}

      🐛 **Potential Bugs:** {{potential_bugs | length}} detected

      {% else %}

      ✅ **Bug Detection:** Clean analysis

      {% endif %}


      ## 📋 Overall Recommendation

      {{recommendation | truncate(200)}}


      **🔗 Links:**

      • <https://github.com/{{repo_owner}}/{{repo_name}}/pull/{{pr_number}}|View PR
      #{{pr_number}}>

      • <{{review_issue_url}}|AI Review Summary Issue>


      _Powered by PlugPipe LLM GitHub MCP Integration_

      '
  outputs:
    slack_notification: '{{slack_result}}'
  id: step_4
  uses: name
  with: {}
- name: record_review_metrics
  plug: monitoring_prometheus
  config:
    prometheus_url: http://prometheus:9090
    job_name: ai_code_review
  inputs:
    operation: record_multiple_metrics
    metrics:
    - name: plugpipe_ai_pr_review_completed
      value: 1
      labels:
        repository: '{{repo_owner}}/{{repo_name}}'
        pr_number: '{{pr_number}}'
        author: '{{ai_review.author}}'
    - name: plugpipe_ai_security_issues_found
      value: '{{security_issues.total_issues}}'
      labels:
        repository: '{{repo_owner}}/{{repo_name}}'
        pr_number: '{{pr_number}}'
    - name: plugpipe_ai_performance_concerns
      value: '{{performance_concerns.total_concerns}}'
      labels:
        repository: '{{repo_owner}}/{{repo_name}}'
        pr_number: '{{pr_number}}'
    - name: plugpipe_ai_bugs_detected
      value: '{{potential_bugs | length}}'
      labels:
        repository: '{{repo_owner}}/{{repo_name}}'
        commit_range: HEAD~3..HEAD
  outputs:
    metrics_recorded: '{{prometheus_result}}'
  id: step_5
  uses: name
  with: {}
summary:
  format: table
  doc: Pipeline execution summary for github-ai-pr-review-demo
copyright:
  owner: PlugPipe Team
  year: 2025
  notice: Copyright © 2025 PlugPipe Team. All rights reserved.
license: MIT
license_url: https://opensource.org/licenses/MIT
spdx_license_identifier: MIT
