# PlugPipe Secret Management Configuration
# This file configures how PlugPipe connects to various secret providers

# File-based secrets configuration
secrets_file_path: "secrets"  # Directory containing secret files

# HashiCorp Vault configuration
vault:
  enabled: false  # Set to true to enable Vault integration
  url: "http://localhost:8200"
  # token: "your-vault-token"  # Can also use VAULT_TOKEN environment variable
  secret_path: "secret/plugpipe"  # Default path for secrets

# AWS Secrets Manager configuration
aws_secrets:
  enabled: false  # Set to true to enable AWS Secrets Manager
  region: "us-east-1"
  # AWS credentials should be configured via AWS CLI, IAM roles, or environment variables

# Azure Key Vault configuration
azure_keyvault:
  enabled: false  # Set to true to enable Azure Key Vault
  # vault_url: "https://your-vault.vault.azure.net/"
  # Authentication uses DefaultAzureCredential (Azure CLI, Managed Identity, etc.)

# Kubernetes Secrets configuration
kubernetes_secrets:
  enabled: false  # Set to true to enable Kubernetes secrets
  namespace: "default"  # Default namespace for secrets
  default_secret: "plugpipe-secrets"  # Default secret name

# Security settings
security:
  # Log secret access (be careful - don't log actual secret values)
  log_secret_access: true
  
  # Fail fast on missing required secrets
  fail_on_missing_secrets: true
  
  # Cache secrets for performance (in memory only)
  cache_secrets: true
  cache_ttl: 300  # 5 minutes
  
  # Allowed secret providers (restrict if needed)
  allowed_providers:
    - env
    - file
    - vault
    - aws_secrets
    - azure_keyvault
    - k8s_secret